backend:
  name: git-gateway
  branch: main
media_folder: "_site/assets/images/"
public_folder: "/assets/images/"
collections:
- name: "projects"
  label: "Projects"
  folder: "src/projects"
  create: true
  slug: "{{slug}}"
  fields: # The fields for each document, usually in front matter
    - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/base-project.njk" }
    - { label: "Project Template", name: "projectTemplate", widget: "number" }
    - { label: "Tag", name: "tag", widget: "list", default: ["project"] }
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Subject", name: "subject", widget: "string" }
    - { label: "Description", name: "description", widget: "string" }
    - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD" }
    - { label: "Hero Image", name: "heroImage", widget: "image" }
    - { label: "Hero Image Alt", name: "heroImageAlt", widget: "string" }
    - { label: "Website", name: "website", widget: "string" }
    - { label: 'Project Images', name: 'body', widget: 'markdown' }
